# Generated by Django 2.1.4 on 2018-12-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('imageUrl', models.CharField(default='', max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('precio', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('Celulares', 'Celulares'), ('ComponectesPC', 'ComponectesPC'), ('Monitores', 'Monitores'), ('Accesorios', 'Accesorios')], default='celulares', max_length=255)),
            ],
        ),
    ]
