# Generated by Django 2.1.4 on 2018-12-13 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaElectronica', '0002_auto_20181213_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tienda',
            old_name='dirección',
            new_name='direccion',
        ),
    ]
