# Generated by Django 2.1.4 on 2018-12-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaElectronica', '0003_auto_20181213_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedor',
            name='id',
        ),
        migrations.AddField(
            model_name='vendedor',
            name='correo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='username',
            field=models.CharField(default='', max_length=30, primary_key=True, serialize=False),
        ),
    ]
