# Generated by Django 2.1.4 on 2018-12-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaElectronica', '0004_auto_20181213_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='password',
            field=models.CharField(default='', max_length=40),
        ),
    ]
