# Generated by Django 2.1.4 on 2018-12-13 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaElectronica', '0006_auto_20181213_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedor',
            name='nombre',
        ),
    ]
